project_id = "heevwrvyglhhydyinkol"

[functions.extract-po-data]
verify_jwt = false

[functions.extract-product-specs]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.sync-sap-inventory]
verify_jwt = false